# action.yml
name: 'Stratis Fedora Container Action'
description: 'Run steps in Fedora container'
inputs:
  options:
    description: 'Options'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
